name: Deploy Next.js to EC2

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy and start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          script: |
            # Navigate to the project directory
            cd /var/www/html/reconcile-ai-fe

            sudo git config --global --add safe.directory /var/www/html/reconcile-ai-fe

            # Pull latest changes
            sudo git pull origin main

            # Install dependencies
            sudo npm install

            # # Build Next.js application
            # sudo npm run build

            # # Reset ownership for Nginx
            # sudo chown -R www-data:www-data /var/www/html/reconcile-ai-fe

            # Restart Nginx
            sudo systemctl restart nginx

            npm run dev
