name: Deploy Next.js to EC2

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy and start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          script: |
            cd /var/www/html/reconsile-ai-fe

            git pull origin main

            npm install

            npm run build

            # Restart Nginx
            echo "${{ secrets.EC2_PASSWORD }}" | sudo -S systemctl restart nginx
