name: Deploy Next.js to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy and start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          script: |
            cd /var/www/html/reconcile-ai-fe

            git reset --hard HEAD
            git clean -fd
            git pull origin main --force


            git pull origin main

            npm install


            tmux send-keys -t 0 C-c
            tmux attach -t 0

            # chmod -R 755 /var/www/html/reconcile-ai-fe/.next

            PORT=3000 npm run dev
