name: Collect DORA Metrics
on:
  schedule:
    - cron: ‘0 * * * *’  # Runs every hour
  workflow_dispatch:  # Allows manual trigger
jobs:
  collect-dora-metrics:
    runs-on: reconcile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Custom Script to Collect and Push Metrics
        run: |
          chmod +x .github/scripts/collect_dora_metrics.sh
          ./.github/scripts/collect_dora_metrics.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSHGATEWAY_URL: “http://3.73.6.29:9091”
